# Generated by Django 4.1.3 on 2022-11-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0002_category_jobpost_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='Company name')),
                ('company_profile', models.TextField(blank=True, verbose_name='Company profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='company',
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='jobdescription',
            field=models.TextField(blank=True, verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='jobtitle',
            field=models.CharField(max_length=150, verbose_name='Job Title'),
        ),
    ]
