# Generated by Django 4.1.3 on 2022-12-03 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobpost', '0003_company_remove_jobpost_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jobpost.company', verbose_name='published by company'),
        ),
    ]
