# Generated by Django 4.1.3 on 2022-11-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadcv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadcv',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploadcv',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
